### ISSUE TITLE
Location & Refresh headers.

### ISSUE THREAD

**Issue by hisorange** [arvgta/ajaxify#10]
Maybe this is not a popular issue, but still can cause some unexpected error: 

```
/login # GET send a form from this address
/login/process # POST form being processed and the response will be a Location: /login/success
/login/success # GET content being loaded nicely from here
```

which displays nicely except the URL in the browser stays on the processing page where it got redirected from.

The issue runs bit wild when you fail the form validation on php side more then once, because the flow will be this. (worth to mention I use the HTTP_REFERER header to redirect the user where it come from and thats why it goes nuts)

```
/login # GET the form
/login/process # POST the form with HTTP_REFERER /login
/login # GET but the title bar say /login/process
/login/process # POST the form again but this time the HTTP_REFERER will be the /login/process
/login/process # GET since this is the redirection
```

Maybe the possible solutin is to check out the response's location header if any and then push the state to the history? 

Once long long ago I wrote a similar script but in those ancient times there were no history api whatsoever so it's not perfectly related and I am not really up-to-date with the current js mechanism but i used to check if the response have location or refresh header, if there were location header changed the address bar (was a window like desktop in js) and pushed that url into the history. And when there was a refresh header hmmm I simply dont remember how i handled that was something like parsing the seconds out from the refresh header and then put to setTimeout and actualy simulated a refresh in ajax and redid the query if the history not changed in mean time since.... something like that.

I hope this gona be more helpful then stressful. The plugin is a great work and maybe I use it wrongly and this issue not even exists if so then sorry @@

**Comment by arvgta** [comment]
Hi Hisorange,

Thanks for raising this issue!

No problem.  If it's in the scope of what many users will expect, then I'll attempt to handle it :-)

So the questions are:
- Does this pertain to many use cases?
- How do you fetch the location header in jQuery/JavaScript and override the currentURL with it?

Do you think there are many use cases for this issue?

If yes, I would like to catch all of them at the most general level possible, i.e. at the "Pronto" level.

First thing I'll do is research, whether it's possible at all to fetch the location header in jQuery/JavaScript...

Raised this thread: https://forum.jquery.com/topic/can-getresponseheader-get-the-server-side-http-referrer

Also found this: 

http://stackoverflow.com/questions/199099/how-to-manage-a-redirect-request-after-a-jquery-ajax-call?lq=1
(is that your use-case?)

As far as a refresh header is concerned - never used it before...  What should be done in that case?

Btw - how do you edit your GitHub replies so nicely (e.g. insert code) - I can see no editor?

After researching this issue for a while now, my gut-feeling says that your use case is the exception to the rule.
According to the excellent thread at stackoverflow, the normal case is that modern browsers should handle this transparently (at least according to the W3C specification)

Thanks!!

**Comment by hisorange** [comment]
I spend some hour to understand the problem, and it looks like you could actualy catch the Location header easly with an 

``` js
$( document ).ajaxSuccess(function( event, xhr, settings ) {
    console.log(xhr.getAllResponseHeaders());
});
```

I need more test to simulate the request in different scenarios, where the location url and action url is relative / absolute to see if its happens on non CORS request as well.

will update this soon, 

Btw you can learn comment styling if you click to right top corner's link: "Comments are parsed with GitHub Flavored Markdown" ;)

Update 1: Digging into the problem and trying to find related articles http://softwareas.com/the-weirdness-of-ajax-redirects-some-workarounds

**Comment by arvgta** [comment]
Thanks very much!  (completely oversaw the "GitHub Flavored Markdown" bit)

Yes, I think it's feasible very easily and selectively with:

```
xhr.getResponseHeader('Location');
```

The only thing that's important is that it doesn't override default behaviour of browsers in any majority of use cases that is sound.

Maybe another jQuery option? e.g.

```
forms: redirect
```

That might be the "best of both worlds"?

Yes, that would be site-internal, right, not CORS?

(Am off til the evening, please don't be surprised)

**Comment by hisorange** [comment]
Nom nom, I set up a test suite for the problem and was able to reproduce with relative urls which are not affected by the CORS, you can see how the event flows.

```
// Post any kind of form data and magic will show off.
// Get any redirection, the url will stay the same and will display the wrong page if the site being reloaded.
http://laugh.hu/test.php 
```

Oh and I pushed your plugin to the jsdelivr.com CDN for faster and always safe loading, you can controll your versions through github.

**Comment by hisorange** [comment]
Explaining the problem it's happen not only on the post but on get requests too, since the browser automaticly follows the redirection to the right content will be delivered but the history api need to catch up with the changed location, so right now need to find a way where the api can observe the location.

**Comment by arvgta** [comment]
Thanks!

So simply speaking, the "History API" bit just has to catch up with the redirects - no problem...

(haven't had a chance to look at the demo, thanks a million for your effort!)

**Comment by hisorange** [comment]
Sounds simply but I'm not sure it's really catchable without serverside help, since the headers which being provided to the api is the final header which does not contain any information about redirection or location of the content.

I think the only walkable way a callback which get the xhr informations fetch an X-Location header and push that state.

**Comment by arvgta** [comment]
Hi Hisorange,

http://stackoverflow.com/questions/199099/how-to-manage-a-redirect-request-after-a-jquery-ajax-call?lq=1

Please have another look - among all those answers, there must be similar use case.

I would like to stay pure jQuery / JavaScript - so if server-side customisation is necessary, and as nobody has raised this before and is joining in at the moment, my feeling says it pertains to less than say 50% of the users...

Feel free to derive the code from the plugin to specialise to your needs.

The salient code bits are (currently):

Sub-plugin:

```
 $.lAjax = function (hin, p, post) {...
```

You can see that I'm delegating in there already to:

```
function _isHtml(x) {
```

...which gets the XDR as a parameter and calls 

```
getResponseHeader()
```

You could derive and do something similar for 'Location' on the client side.

As far as the server-side is concerned - no idea - you know better...

Let me know, if that helps... (am off til tomorrow)

**Comment by arvgta** [comment]
Just a quick note: https://forum.jquery.com/topic/can-getresponseheader-get-the-server-side-http-referrer

This thread just was answered.  That implies that there definitely is need for a co-ooperative solution between the server and client.

As I would like to stay "pure JS / jQuery" - I'll leave it for now.

Would suggest in your use case, if you like this plugin, to derive from it as described above.

Would have loved to provide a general purpose solution, but don't think it can be done in pure jQuery...

**Comment by hisorange** [comment]
Yep, thought the same, so I think i gona implement a hook where the server will tell the content's address and if its mismatch the ajax location then push that state.

As I see there isnt any working solution for this either, but nah at W3C things going really really slowly /html4/ ~ so thanks for the efforts. ;)

**Comment by arvgta** [comment]
Hi Hisorange,

Thanks for your effort, too  
This issue is surely interesting for one or the other user in future.

If you manage to get it done purely server-side, that's probably cleaner than a co-operative approach between the server and this plugin.

Well, we tried!

Feel free to tell others about your experience by posting back, whether you got it working or not.

Also, if you happen to choose a co-operative hook instead, please tell me what kind of hook I could provide in the plugin (I'd have to document this issue, maybe with a demo page, at http://4nf.org/)

What percentage of plugin users do you think is affected?

Cheers and
Kind regards

**Comment by hisorange** [comment]
I worked out some more page on my current project, and the redirect back happens pretty often and ofc other kind of redirections as well. Right now I have to work over some translations on my page but when it done will try to make something like:

``` js
function callback(xhr)
{
xhr.getHeader('Route')
// push the state
}
```

I don't know yet how I can handle it, need to dig into the source code more and more :D But I read a bit more about it and looks like it's a common problem with ajax neither of the plugin can handle it with pure js. But the redirect response is fairy common as well, just for example the user clicks to the Upload link but not logged in, then need tor redirect to the login page. @@

**Comment by arvgta** [comment]
If you need any help reading the source code, please let me know (finding out, where to hook into it...)

Also, as mentioned before, if you see the possibility of generalising the hook, so it can be provided it in general-purpose fashion...

When looking at your callback above, the only thing bespoke is the

```
'Route'
```

...so that could be soft-coded as a jQuery option in the plugin interface, the rest / skeleton of the mechanism being built-in...

Interesting to know, that you think this issue will pertain to many users.  That makes this issue pretty important in terms of scope / coverage of the plugin.

Greetings

**Comment by hisorange** [comment]
I think I found the most user friendly solution since the ajaxification is about to load HTML faster the most useful to deploy the HTML's meta. Luckly the canonical tag is spreading across the web, you can read a [wiki](http://en.wikipedia.org/wiki/Canonical_link_element) article about it.

I was thinking about smth like this:

``` js
$('#content').ajaxify({ canonical: true });
```

Where the plugin will check out if the loaded content's contain any canonical meta attribute, and push that's state if differs from the requested.

``` html
<!-- absolute path -->
<link rel="canonical" href="http://domain.com/contents-real-url">
<!-- or relative path -->
<link rel="canonical" href="/contents-real-url">
```

What dou you think is it madeable? 

This doesnt involve server side hacks or usage of non official response codes and since the webpages already containing this meta for SEO purposes, there is no work with it.

**Comment by arvgta** [comment]
Excellent!  Thanks very much!!

Yes, I presume it is feasible.  I would like to resolve issue #12 first though, before "growing" further....
Does this only pertain to redirects in forms?

**Comment by hisorange** [comment]
No, any kind of redirection provides the wrong address, so GET type request as well. This should handle everything.

**Comment by arvgta** [comment]
Thanks!

So, before I start implementing it, just one more question:
- It applies to redirects in general?

That obviously pertains to quite a few users :-)

**Comment by hisorange** [comment]
Yes, I mean if I could describe it would something like this:

```
This feature allows the plugin to detect the resulted content's real address, even if the result was redirected one or multiple times. 
By fetching the result's real address can keep the browser state valid.
```

Ofc the refresh header is a different topic there will be need some more advanced logic, but that will be a different issue :D

**Comment by arvgta** [comment]
Alright, great stuff!

Found out, that I have to re-factor script handling first, before tackling this issue...

It may take a few days...

Any news on issue #11 ?

Cheers!

**Comment by arvgta** [comment]
Implemented and tested :-)

You can see it working if you press the redirect at the bottom of: http://4nf.org/code/pp/ ("Old URL - a redirect")
The address in the "History API" part is updated, the back and forward buttons work properly.

Assuming that we'll create a new issue for "refresh headers", I'll now close this one.

Thanks once more again, Hisorange!

**Comment by wikiloops** [comment]
first of all, thanks again for this - the redirection issue was what led me here in the first place.
I ran into some trouble implementing this, until I noticed that the URL will only get updated after a redirect if there is no "#" or "?" parameter attached to the final page. (see line 734)

This may make sense in some scenarios, it didn't in my case, so I removed the check for the "?" and everything worked fine.

example
user visits test.php
internal check notices page needs to be updated,
redirects to update.php?renew=test 301
/\* does some updating */
redirects to test.php?fresh=true 301
test.php knows internal check can be avoided by reception of "fresh" param
before fix:
     adress bar shows "update.php?renew=test"
after fix
     adress bar shows "test.php" as given in canonical  - great :)

**Comment by arvgta** [comment]
Hi Wikiloops!

Thanks for your kind feedback and the thorough testing!

First of all - here's the line of code you're wondering about:

```
if (canURL && canURL != url && !url.iO('#') && !url.iO('?')) url = canURL;
```

I double-checked what kind of "canoncical" URL is supplied by Wordpress on dynamic pages with a question mark or hash.  It seems to supply the root URL - without hash or question mark.
That's why I reckon, that for people using an ordinary CMS, the above logic is alright.

If there are more users, that disagree and find, that the above logic needs to be amended, I'll be quick to do so :)

Thanks again!
