### ISSUE TITLE
Turbo prefetch

### ISSUE THREAD

**Issue by hisorange** [arvgta/ajaxify#11]
So since the preview problem solved, I ran into something funy :P

What's happen when you pulling your mouse across the page and it hovers some 'delete' link? Which are normaly used for ajax but should not being called without the click.

Since the turbo is a reasonable feature the turning off not a solution, to ".no-ajaxy" every link which is harmful is unecessary, just need to add a selector which denies the turbo on the specific link but let the ajaxification happen on click ;)

**Comment by arvgta** [comment]
I'm glad you raised this issue, which I was partially aware of, but hadn't gotten round to lifting, yet ...

Again, similar to what we've done in the Preview issue - providing a solution that is as general as possible, this should be caught at the root.

Probably solved @4nf.org by amending the "Turbo prefetch" algorithm!

I've raised a new issue, that is in the current version - please see issue #12

**Comment by arvgta** [comment]
Hi Hisorange,

I've uploaded the tested code to GitHub now - sorry for the delay.

Please test :-)

**Comment by hisorange** [comment]
Oki, will make a better test suite for this tonight.

**Comment by arvgta** [comment]
Thanks very much!

Any results from the tests?
