### ISSUE TITLE
Slideshow / carousel buggy on Chrome - bounty of €100

### ISSUE THREAD

**Issue by arvgta** [arvgta/ajaxify#128]
**I would like to issue a bounty of €100, payable via PayPal, for anybody, who can offer a generic solution to this bug within the Ajaxify code or has any ideas that lead to the resolution of the bug!**

[Demo on 4nf.org](http://4nf.org/)

<hr />

**How to reproduce the bug:**

Please open Chrome and 4nf.org in the first browser tab.  Then open a second tab, no matter with which URL and keep the focus on it (- i.e. don't put the focus on the first tab with 4nf.org in it).

After about 60 second the slideshow should kick-in.  After a couple of pages iterated by the slider, you should be able to find, that the slideshow slows down considerably...  If you then shift the focus to the first tab with 4nf.org in it, the slideshow resumes its normal speed (only to slow down again afterwards)...

I only was able to re-produce the bug in Chrome, but please shout, if you disagree!
Bug also persists, when I activate old versions of Ajaxify on 4nf.org - really weird...

<hr />

**Salient code**

- ["slides" sub-plugin](https://github.com/arvgta/ajaxify/blob/new/ajaxify.js#L599) - for slideshow
- ["cd" sub-plugin](https://github.com/arvgta/ajaxify/blob/new/ajaxify.js#L543) - for animations

**Comment by krheinwald** [comment]
Could that be the reason - Idling of background tabs?

https://thenextweb.com/apps/2017/01/26/chrome-throttle-background-tabs-google/

**Comment by arvgta** [comment]
Thanks very much!  Very interesting article!  If that is the reason, then there is nothing to do from an Ajaxify point of view, right?  There are obviously timers running in the background, that might be throttled by the described "Chrome feature".  That would also explain, why reverting to old versions of Ajaxify doesn't change anything...  It would also explain, why I have only become aware of the "feature" recently.  We'll leave this thread as is for a short while for others to join-in, but if we agree on your suggestion as the culprit, I would like to give the bounty to you...  

Thanks again!

**Comment by arvgta** [comment]
@krheinwald - alright, I'm so enthusiastic about your contribution!  Please contact me at arvgta@gmail.com

**Comment by arvgta** [comment]
**Bounty paid successfully!**

@krheinwald - Thanks for saving me loads of time debugging in the dark!  If you like Ajaxify, please contemplate [starring](https://github.com/arvgta/ajaxify) it...

All the best!
