### ISSUE TITLE
Firefox e.originalEvent.state is undefined

### ISSUE THREAD

**Issue by jesserosenfield** [arvgta/ajaxify#139]
Using the following markup:

`<a onclick="window.history.go(-1); return false;" class="icon-close"></a>`

I get the following error:

![screen shot 2017-12-27 at 5 05 30 pm](https://user-images.githubusercontent.com/482945/34394600-38f503e0-eb28-11e7-865b-72932a14e0f6.png)

```
TypeError: e.originalEvent.state is undefined
our-work:127:13
_doRender2
http://localhost:8888/spr/our-work/:127:13
Cd/this.a
http://localhost:8888/spr/our-work/:50:20
$.cd
http://localhost:8888/spr/our-work/:61:8
_doRender
http://localhost:8888/spr/our-work/:122:7
Cd/this.a
http://localhost:8888/spr/our-work/:50:20
$.cd
http://localhost:8888/spr/our-work/:61:8
_render/<
http://localhost:8888/spr/our-work/:104:30
```

**Comment by arvgta** [comment]
Hi Jesse,

please excuse the delay and thanks for the screenshot and detailled issue report.

Does the problem persist or have you got it working in the meantime?

I think Ajaxify sometimes doesn't work on localhost...
(you may want to try it against a "real" webpage)


Thanks!
