### ISSUE TITLE
Add travis support.

### ISSUE THREAD

**Issue by Nenglish7** [arvgta/ajaxify#149]
It is a good idea to test your code to ensure every function is working the way it should.

- https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by arvgta** [comment]
Hi Nicholas,

thanks for starting this thread and the interesting proposal.

I tried reading the docs but don't seem to get it:

How difficult is it to install Travis and what are the benefits?

Thanks again!

**Comment by Nenglish7** [comment]
I usually program with php. It is fairly easy to use with php for sure. I am working on a branch that will allow  travis support for JavaScript with the repository. All you need to do is add the Travis Ci service in order for it to work. Once i finished ill create a pull request and you can review the changes.

**Comment by Nenglish7** [comment]
Also if you do not won't to use Travis Ci their are some other services like AppVeyor and Codacy. It is really based on preference.

- https://www.appveyor.com/
- https://www.codacy.com/

**Comment by arvgta** [comment]
Hi Nicholas,

you're right, I don't want to use this in order to keep things simple...

Thanks anyway!
