### ISSUE TITLE
ajaxify vs joomla-mailcloak

### ISSUE THREAD

**Issue by woeps** [arvgta/ajaxify#16]
Hi,
_first I have to say, I really really appreciate the work you've done. You saved me like hundreds of hours! Thanks a lot!_

Lately I work on a joomla-project which needed content-fetching via ajax-requests. I implemented your script in a template and it worked like a charm!

BUT: It seems to **crash** if the content to load includes a **cloaked mailto-link** by the default **joomla-component**. (which uses inline-js to print out the mail to the document to protect it from spambots)
The console gives me this **error**:

```
Error: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMHistory.pushState]
```

After that, the browser stays in "loading-state" and only renders an unstyled mailto-link containing the mailadress.

_If I remove the inline-js (by turning the component off in the joomla-backend) or set ajaxify's "inline"-option to false, the script works like it's supposed to be, but this way the mailadress isn't readable or not protected._

Would you have some insight where to look first to resolving this behavior?

**Comment by arvgta** [comment]
Hi Woeps!

_Thanks for trying out the plugin and raising this issue!_

**Is it due to the link itself having the "mailto:" protocol or the HTML to be loaded in the target page having the "mailto:" ?**

_Could you (ideally) provide a URL to a test-page, showing the crash scenario?_

**If possible, I would like to deal with it at a plugin level, i.e. unroot the issue.  If not possible, maybe there is a workaround with _inline_ set to _false_ and _inlinehints_ containing the substrings of scripts to be fired...**

Thanks again and 
Kind regards

**Comment by woeps** [comment]
I think the "mailto:" itself isn't the problem but the way the mailadress gets presented to the browser. An inline-script puts the obfuscated mail together and prints it to the document wich results in something ugly like:

```
<body>
<!-- some content -->
<script type="text/javascript">
 &lt;!--
 var prefix = '&amp;#109;a' + 'i&amp;#108;' + '&amp;#116;o';
 var path = 'hr' + 'ef' + '=';
 var addy32569 = 't&amp;#101;st' + '&amp;#64;';
 addy32569 = addy32569 + 'w&amp;#111;rld' + '&amp;#46;' + 'c&amp;#111;m';
 var addy_text32569 = 't&amp;#101;st' + '&amp;#64;' + 'w&amp;#111;rld' + '&amp;#46;' + 'c&amp;#111;m';
 document.write('&lt;a class="no-ajaxy" ' + path + '\'' + prefix + ':' + addy32569 + '\'&gt;');
 document.write(addy_text32569);
 document.write('&lt;\/a&gt;');
 //--&gt;\n </script><a href="mailto:test@world.com" class="no-ajaxy">test@world.com</a><script type="text/javascript">
 &lt;!--
 document.write('&lt;span style=\'display: none;\'&gt;');
 //--&gt;
 </script><span style="display: none;">Diese E-Mail-Adresse ist vor Spambots geschützt! Zur Anzeige muss JavaScript eingeschaltet sein!
 <script type="text/javascript">
 &lt;!--
 document.write('&lt;/');
 document.write('span&gt;');
 //--&gt;
 </script></span>
</body>
```

I tried using the selector-option to prevent ajaxify of using this specific object, but it seems the error occurs before this gets taken into account.

Loading the Page (which contains the obfuscated link) directly using the browser's address bar works. But if ajaxify loads the content it totally crashes.

Of cause, if I turn off the mail-obfuscation-option, all scripts work fine. - But I still wanted to at least try to make both things work together.

I tried creating a gist/fiddle/.., but I miserably failed, so I'm sending you a mail with the url.

**Comment by woeps** [comment]
Well, the site is a pain in the ***, 'cause I need to rebuilt an older flash-site using modern plain html+ techniques sticking as close as possible to the original design by somebody else. That's why I needed ajax.

The "code-snippet" gets generated by a joomla core-plugin which is activated by default.
It would be very hard to change it's behavior without hacking the core-code, which may mess up updates in the future. So the easiest thing to do here is just deactivating the mailcloaking-plugin (and if needed - look out for another plugin which does mail-obfuscation in an ajax-compatible way).
_Well, I needed at least to ask if there could be a solution I haven't been aware of..._

Nearly every other page (without a js-obfuscated mailto-link [using document.write()] ) works perfectly fine. :)

---

I ran into another kind of weird issue, which isn't related to this one, but I'm not quite sure if it's worth to raise a new one.. :sa: 

When the following kind of script gets included into a site which ajaxify tries to fetch, it puts out the catch-alert() containing `SyntaxError: missing ) after condition`:

``` javascript
$("#submenu-project-carousel-next").click(function(){
    cval = +counter.html()+1;
    if(cval >= maxSlides){
        cval = maxSlides; $("#submenu-project-carousel-next").prop({disabled: true});
        }
    else if(cval > 1){
        $("#submenu-project-carousel-prev").prop({disabled: false});
        }
    counter.html(cval); 
    });
```

The weird part is, when I change the if-conditions to equal it's fine, using greater (and equal) it crashes. I'm not sure if I'm trying something, which would be called "evil" in the ajax-world again. It should be completely unrelated to this Issue.
I would be very pleased to hear you thoughts on this one too?

I really appreciate your help! 
Thanks a lot!

**Comment by arvgta** [comment]
Hi Woeps!

Thanks for the detailled description of your use-case!
Very stylish site you're building, I hope my plugin will be able to keep your code simple...

First of all, the issue you raised on 4nf.org is done:  
- http://4nf.org/interface/comment-page-1/#comment-25716

Concerning the other issues above, I had a look at the site you're building and it seemed to work immaculately?

Give me a hint, if you still have an idea how the plugin could be improved.

Cheers :-)

**Comment by arvgta** [comment]
Closing this issue - please re-open if problem is suspected in this plugin...
