### ISSUE TITLE
New function _copyAttributes()

### ISSUE THREAD

**Issue by arvgta** [arvgta/ajaxify#162]
A user reported an error being thrown by `_copyAttributes()`

**Comment by arvgta** [comment]
Here is the salient code:

```javascript
function _copyAttributes(el, $S, flush) { //copy all attributes of element generically
    if (flush) //delete all old attributes
        for (var i = el.attributes.length - 1; i >= 0; i--) el.removeAttribute(el.attributes[i].name);

    var attr, attributes = Array.prototype.slice.call($S[0].attributes); //slice performs a copy, too
    while (attr = attributes.pop()) { //fetch one of all the attributes at a time
        el.setAttribute(attr.nodeName, attr.nodeValue); //low-level insertion
    }
}
```

When appied to the handling of (a) content element(s) `$S` can contain no or faulty data...

**Fixed by not applying `_copyAttributes()` to (a) content element(s) for the time being...**

**Comment by Seerver** [comment]
Hi, I wrote you an email.

**Comment by arvgta** [comment]
Thanks for posting back - much appreciated!

For the moment, I have [applied this patch](https://github.com/arvgta/ajaxify/commit/481737f04a8dbbcf71c5d4eeb59a7f3ba9ecf619#diff-9395fad3c7372e47626ee7f892b752a2), as indicated above already...

**Comment by arvgta** [comment]
I have patched this deceptive error in [the latest release](https://github.com/arvgta/ajaxify/releases/tag/7.3.6)

The next question, that comes to my mind is whether this nuissance can be catched earlier, maybe even during initialisation of Ajaxify?

**Comment by arvgta** [comment]
Tested on the two usual sites:

- [4nf.org](https://4nf.org/)
- [Öko-Fakt](http://www.oeko-fakt.de/)

... as well as two more Ajaxify user sites

- [Wil Art](https://www.wilart.nl/)
- and another one

...successfully...

thus closing

**Comment by arvgta** [comment]
Re-opening, because I would like to give the `flush` mechanism another try with this code:

```javascript
if (flush) //delete all old attributes
    while(el.attributes.length > 0)
        el.removeAttribute(el.attributes[0].name);
```

**Comment by arvgta** [comment]
[Once content elements consistency is validated beforehand as described in this issue](https://github.com/arvgta/ajaxify/issues/169), it seems that there are no more errors / warnings including such in the `flush` mechanism.  However, if there is a more elegant (pure jQuery) style to handle the copying of attributes, then please let me know!

Closing...
