### ISSUE TITLE
Automation of minification / uglify (with "gulp")

### ISSUE THREAD

**Issue by arvgta** [arvgta/ajaxify#176]
The user who has proposed this issue is prepared to share the code to perform this simplification soon.

The proposed feature will be a significant simplification to the process of [minifying Ajaxify's code](https://4nf.org/minify/), when a user wants to derive from it.

**Comment by arvgta** [comment]
ToDo

**Comment by edito** [comment]
### Gulp minification

Before you proceed using gulp in terminal, gulp command line interface has to be installed globally with (terminal) commands:

`npm install -g gulp`
`npm install -g gulp-cli`

If something goes wrong with installation check [this link](https://gulpjs.com/docs/en/getting-started/quick-start) for npm requirements of gulp.

Next step is opening terminal path to gulp folder (_folder with required files is currently only inside [my fork of ajaxify repository](https://github.com/edito/ajaxify)_) that is placed inside repository and typing `npm install`. Node package manager will install all required packages that are necessary for minification process. After this process is finished you type `gulp` to minify ajaxify any time. 

There are some aditional tasks like `gulp w` to run watcher that is tracking changes of source file and does minification automatically after saving file, `gulp dev` and  `gulp prod` (_commented inside gulpfile.js_). 
Code inside gulpfile.js is also well commented, so everyone can tweak stuff for its own needs.

[This video](https://youtu.be/FKYQT8pYEQA) can be also helpful.

**Comment by arvgta** [comment]
Deferred, as I have no suffer pressure at the moment, because the [specified minification process](https://4nf.org/minify/) only takes about 10 minutes anyway
