### ISSUE TITLE
My first semaphore...

### ISSUE THREAD

**Issue by arvgta** [arvgta/ajaxify#178]
**...in a JavaScript environment.**

This is the issue of ["Edin's ideas"](https://github.com/arvgta/ajaxify/issues/173) which I would like to tackle first.

<hr>

[Original reporting of the bug](https://4nf.org/prefetch/comment-page-1/#comment-66928):

> There is no need to prefetch page if link is already clicked anyway.

<hr>

The bug was reproduced on several sites including:

- [SitForm](http://topalovic.ml/en)
- [4nf.org](https://4nf.org/)
- [Öko-Fakt](http://www.oeko-fakt.de)
- [various sites from the 4nf.org demos page](https://4nf.org/demos/)

**Comment by arvgta** [comment]
This is [a subset of this larger issue](https://github.com/arvgta/ajaxify/issues/179) and was solved [during this commit](https://github.com/arvgta/ajaxify/commit/320e26f196c1ea29868bf19cb877a7a8f03d8490#diff-9395fad3c7372e47626ee7f892b752a2) by enabling a new semaphore mechanism, which prevents thrashing on the same URL..  

**Because enabling the semaphore was placed in the common `_request()` handler, in addition to normal click requests, GET and POST of form requests are also locked....**

<hr>

**New code**

In the (common) `_request()` handler, the following code enables the semaphore:

 ```javascript
$.rq("!"); //we're serious about this request - disable further fetches on same URL
```

In the `$.rq()` sub-plugin, the following changes were made (second constraint of the OR condition):

 ```javascript
if(o === "=") { 
    return h === currentURL //check whether internally stored "href" ("h") variable is the same as the global currentURL
    || h === l; //or href of last request ("l") //this constraint is new
}
```

...and...

 ```javascript
if(o === "!") return l = h; //store href in "l" (last request)
```

**Comment by arvgta** [comment]
**Tested to work fine...  Thus closing...  If you have any funnies, please re-open**

**Comment by edito** [comment]
Just to mention that current semaphore, altogether with [**f876773**](https://github.com/arvgta/ajaxify/commit/f87677355f7ff2c1ce00957b28078b930d367c45) fix, covers only **Option 2** -> _Situation 1_ from #179 issue, which caused most of the refreshes. While **Option 1** and **Option 2** -> _Situation 2_ are not covered yet. 

In case of [partner site](http://www.oeko-fakt.de/), where refresh is set to false, the only thing that causes periodic refresh is **Option 2** -> _Situation 2_ from #179.
