### ISSUE TITLE
Body swap option

### ISSUE THREAD

**Issue by arvgta** [arvgta/ajaxify#197]
...can now be activated by _not_ passing any arguments in the main selector i.e. an empty selector:

    jQuery().ajaxify();

Ajaxify will then perform a full `body `swap every time around...

**Comment by beratgashi** [comment]
Hi Arvind,

How can we make ajaxify request to reload div after ajax form is submitted?

**Comment by arvgta** [comment]
No news is good news, so I reckon, this has widely been accepted.  Thus closing for the moment...
