### ISSUE TITLE
Redirect is removing numbers from end of URL

### ISSUE THREAD

**Issue by kcwebdesign** [arvgta/ajaxify#198]
We have some URLs like this...

https://stagemvp.gotohear.com/playlist/11

They're a nice version of a query string where 11 is the id of the playlist. When they get Ajaxed the pages show ok but in the URL bar and canonical meta the 11 is missing. 

It looks like after the page has loaded the url that gets written back in has had the numbers removed. Can the code be changed to avoid this please?

We're using version 7.5.5

Thanks
Paul

**Comment by arvgta** [comment]
Hi Paul,

as mentioned on 4nf.org in a comment, we're evaluating, whether this is a bug in Ajaxify...

EDIT:  I don't suppose you could supply a link to your site, or a test site?

Additionally, if you would like to accelerate the process, you could check, whether the bug also happens [with the latest version](https://cdn.jsdelivr.net/gh/arvgta/ajaxify@7.6.2/ajaxify.min.js)?

Thanks and regards,
Arvind

**Comment by kcwebdesign** [comment]
Thanks Arvind. 

Yes, same issue on latest version.

Our site is behind a login. I can send you one via email if you let me have your address.

**Comment by arvgta** [comment]
Thanks for testing the latest version, Paul.

My email-address is arvgta@gmail.com

**Comment by arvgta** [comment]
Solved...

The option `canonical` was set to `true` - solved by setting:

    canonical: false
