### ISSUE TITLE
Window "popstate" fires twice when clicking on browser back button

### ISSUE THREAD

**Issue by menturion** [arvgta/ajaxify#203]
Window "popstate" event fires twice in line #699...

https://github.com/arvgta/ajaxify/blob/3ecb0078308dd25497d6e3869a355d315a62849c/ajaxify.js#L699

... when clicking on the browser's back button which finally leads to a reload of the requested page. 
This "popstate" issue is well known.

**Comment by arvgta** [comment]
I have already [asked you here](https://github.com/arvgta/ajaxify/issues/202#issuecomment-619114920), not to spawn any more issues.  If you continue to do so, I will have to block you, because I regard this as spamming...

**Comment by menturion** [comment]
Please don't hesitate to inform Github.
I am not spamming but just filing existing issues regarding your script.

All reported issues are still active, including this one https://github.com/arvgta/ajaxify/issues/202#issuecomment-619114920, and can be verified. 

So if I will find any further issue I will post it here for the sake of your script and the community using your script.
