### ISSUE TITLE
Hasnat's suggestions

### ISSUE THREAD

**Issue by arvgta** [arvgta/ajaxify#217]
(To be container for more GitHub child issues)

- https://4nf.org/more/comment-page-1/#comment-166664

<hr>

Suggestions made:

- [Improve Adsense support](https://4nf.org/dollars/)
- Option to exclude entire pages from being ajaxified
- Language translation
- Interleave code snippets in documentation

**Comment by mixmtech** [comment]
There is one more suggestion from me. Sometimes it takes time for the server to respond, within this time user cannot notice that request has been already sent. It's a bit confusing. Also sometimes it responds so quickly that the user doesn’t even realize that its content has changed. It's also a problem for user experience. 

I think, a simple preloader or any indicator (like Snackbar / Toast) can solve this issue.

**Comment by arvgta** [comment]
Thanks Hasnat!

These are all suggestions for further growth in functionality, which I will take care of, once I'm convinced, that Ajaxiify is "healthy" i.e. there are no other errors inside...
