### ISSUE TITLE
JS Pure

### ISSUE THREAD

**Issue by alexolliveira** [arvgta/ajaxify#220]
Hi! Is there a way to implement Ajaxify without using jQuery? I would like to use JS Pure.

**Comment by arvgta** [comment]
Yes, of course.  The latest Ajaxify versions are written in pure JS and you can use pure JS on your site when implementing it...

Have a look at these two example site:

- https://www.360zuid.nl/

and

- https://www.dwazeherderdeal.nl/

Feel free to ask any further questions, if you like!

**Comment by alexolliveira** [comment]
Wow! Great! I'll test it now! Thanks for answering, brow!
