### ISSUE TITLE
URL Levels

### ISSUE THREAD

**Issue by alexolliveira** [arvgta/ajaxify#221]
I would like to using a 2nd friendly url level, but I'm having some problems.
Eg.:
**Here, with 1 url level, Ajaxify works well:**
_myapp.com/products_
_myapp.com/faq_
_myapp.com/contact_

**But here, using a 2 or 3 url level, not:**
_myapp.com/products/web_
_myapp.com/products/web/pwa_

How can I solve it?

**Comment by arvgta** [comment]
Do you have a link to your (test) site?

**EDIT:** 
Just came to my mind, that there are actually examples on 4nf.org, of what you're trying to get working:

(Nested under:  https://4nf.org/more/)

- https://4nf.org/more/about/
- https://4nf.org/more/privacy/
- https://4nf.org/more/thanks/

So I would reckon, that what you're describing is specific to your site?
Are you working with a local installation, or an online one?

**Comment by alexolliveira** [comment]
I already solved it. Thank you!
