### ISSUE TITLE
why am i getting error [Cannot read properties of undefined (reading 'ael')]

### ISSUE THREAD

**Issue by oubihis** [arvgta/ajaxify#226]
Hello @arvgta, 

First i want to thank you for this plugin, my my question was why i get error **Cannot read properties of undefined (reading 'ael')**.
in this part i don’t know what is role of 'ael'.

<img width="1059" alt="Screen Shot 2022-08-05 at 15 50 22" src="https://user-images.githubusercontent.com/29286895/183104250-c44d5a6e-d039-4e58-ba25-310fe4ad7622.png">

Thanks again

**Comment by arvgta** [comment]
Hi there,

Do you have a link to your (test) site?
(I'm afraid I can't tell just like this)

**Comment by oubihis** [comment]
yes
check [here](https://www.radioj.fr/).

**Comment by arvgta** [comment]
Thanks.  How can I reproduce the error on your site and where can I find your Ajaxify call?

**Comment by oubihis** [comment]
you welcome ,
just check console after click any link.
you can find files in : 
[ajaxify](https://www.radioj.fr/wp-content/themes/sounder-child/js/ajax.js)
[for event function ](https://www.radioj.fr/wp-content/themes/sounder-child/js/jquery.ba-hashchange.min.js)

**Comment by arvgta** [comment]
Just as a note - your site seems to be a bit instable.  There are all sorts of other error messages.
However, you might want to try specifying:

- `intevents: false`

in your Ajaxify call...

**Comment by oubihis** [comment]
what is role of **_intevents: false_**

**Comment by arvgta** [comment]
It disables the whole code around the `ael` handling

**Comment by oubihis** [comment]
yes, it’s  working, thank you.

But is returning new error. i dont now if this normal or not.

<img width="1163" alt="Screen Shot 2022-08-05 at 16 46 07" src="https://user-images.githubusercontent.com/29286895/183113862-4982dcf7-f7c4-4db6-8d0d-4fb4610d831a.png">

**Comment by arvgta** [comment]
Glad we got your first issue solved.
I believe what you just posted is a different bug.
You might be swapping something without content or similar?

**Comment by arvgta** [comment]
Just had a look at the Ajaxify code - your last error is coming from the swapping of the page title...

(in the following line:)

`if(title = Ay.fn("title")) qs("title").innerHTML = title.innerHTML;`

**Comment by oubihis** [comment]
yes 👏 , i will  have title tag 

`<title>.....</title>`

**Comment by arvgta** [comment]
Please try specifying a `title` tag on all of your subpages and see, if the error goes away?

**Comment by oubihis** [comment]
i think 💭 problem coming from wp-rocket plugin cache, because create another title tag.
so i add [0] for first title in ajaxify file.

`if(title = Ay.fn("title")[0]) qs("title").innerHTML = title.innerHTML;`

it is work great 👍 😊.

**Comment by arvgta** [comment]
Well if that fix works for you - that's fine!  Good work!
