### ISSUE TITLE
Issue with CSS

### ISSUE THREAD

**Issue by misog** [arvgta/ajaxify#229]
Hi, here is the original issue I had:

Code: https://phpsandbox.io/e/x/nznhx?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=no&openedFiles= 
Actual site: https://nznhx.ciroue.com

The CSS is broken after ajaxify reload (JS works)

**Comment by arvgta** [comment]
Yes, I can reproduce the bug, when pressing:

- Reload with ajaxify

The page(style) breaks on reload.
However, I have no idea why?
Where is the CSS you're talking about?

**Comment by misog** [comment]
The plugin owner changed CDN or something, here it is https://nznhx.ciroue.com
Working:
![Screenshot from 2022-08-17 20-39-19](https://user-images.githubusercontent.com/6667651/185217586-5fe4fa6d-9da7-4c18-a4bd-078c992b9012.png)

Not working:
![Screenshot from 2022-08-17 20-39-28](https://user-images.githubusercontent.com/6667651/185217600-2718cc64-439c-4b67-bc01-b3f029746400.png)

Code:
```html
<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/picmo@latest/dist/umd/index.js"></script>
    <script src="https://4nf.org/ajaxify.js"></script>
    <script>
        let ajaxify = new Ajaxify({
            verbosity: 100,
            prefetchoff: true,
        });
    </script>
</head>
<body>
    <a href="/?reload=<?=microtime(true)?>">Reload with ajaxify</a>
    <div class="pickerContainer"></div>
    <script>
        var container = document.querySelector('.pickerContainer');
        var picker = picmo.createPicker({
            rootElement: container
        });
    </script>
</body>
</html>
```
