### ISSUE TITLE
address line not change if redirected from server

### ISSUE THREAD

**Issue by sapsan** [arvgta/ajaxify#23]
Hello.

Example:
1. click on ajaxify link "/stat/detailed" 
2. got redirect to "/stat/detailed/all/" from PHP script
3. correct html recived
4. address line contain the same "/stat/detailed" 
5. but if F5 pressed I see "/stat/detailed/all/" at adress line

**Comment by arvgta** [comment]
Hi Sapsan,

please have a look at issue #10 before we go on - thanks!

To cut a long story short, HisOrange and I decided to fetch the correct new address from the target's

```
canonical
```

tag.

(Labelled "duplicate" for the time being)

**Comment by sapsan** [comment]
Yes, `<link rel="canonical" href="/stat/detiled/all">` helped.
Thanks.

**Comment by arvgta** [comment]
Thanks Sapsan!

Is the solution with

```
canonical
```

alright, or can anybody think of a more elegant and maybe more generic solution?

**Comment by sapsan** [comment]
Maybe put some smart function into event handler **_pronto.load**_ ?
If I was not used **_canonical**_ I got only **_/stat/detiled**_, but when I press F5 after page loaded then I got **_/stat/detiled/all**_ inside the address field. So, this value stored somewhere...

**Comment by arvgta** [comment]
Hi Sapsan,

had to research, what **F5** does - it **re-loads** a page if changed.
Hmmh, I'm wondering where the value in the **Pronto section** of this code is to be found:
- https://github.com/arvgta/ajaxify/blob/new/ajaxify.js#L492 (and following)

?

```
currentURL 
```

is a Pronto-global.  Apart from that, the event info is passed down the ladder all the way from 

```
_click(...)
```

to

```
_doPush(...)
```

I believe that, in course of the issue #10, HisOrange and I tested other ways of accessing and pushing the second URL with **pushState** in vain.  I think a re-direct does not result in raising a Pronto event.

**Comment by sapsan** [comment]
I mean real redirected url stored somewhere in browser.

**Comment by arvgta** [comment]
Thanks Sapsan - I will research that...

EDIT:  Found this, which doesn't look too promising:
- http://stackoverflow.com/questions/11698178/how-can-i-get-the-redirect-url-using-javascript

Also double-checked, whether this was raised as an issue in the latest Pronto versions - it hasn't : 
- https://github.com/benplum/Pronto/issues?q=is%3Aissue+is%3Aclosed

So I reckon, that the solution with

```
canonical
```

is reasonably elegant, as 301 redirects are related to that attribute...
