### ISSUE TITLE
Script not executing loaded from page b

### ISSUE THREAD

**Issue by khanakia** [arvgta/ajaxify#231]
I have 2 pages
1. Page A
2. Page B

When i click page b link it loads the page b but the script1.js has some conditional function does not runs at all.

Basically i have this script i want to rerun this script on every page change.
```
<script async data-main="//cms.tutor.devs/a/theme1/assets/dist/main" src="[//cms.tutor.devs/a/theme1/assets/lib/requirejs/require.js](http://cms.tutor.devs/a/theme1/assets/lib/requirejs/require.js)" onload="window.dispatchEvent(new Event('requirejs'));"></script>
```

**Comment by arvgta** [comment]
Hi, thanks for your enquiry.
Have you tried alwayshints?

**Comment by khanakia** [comment]
Yes just tried not working. I will create a demo and send to you.

**Comment by arvgta** [comment]
Thanks, much appreciated.
I do not have full internet access at the moment... Just to let you know.

If you like in the meantime, please check whether it's the same with other
Ajaxify versions. Which version are you using?

**Comment by khanakia** [comment]
latest one

**Comment by arvgta** [comment]
Please contemplate making a brief check against e.g. version 8.2.1

**Comment by khanakia** [comment]
I have created some demo.
https://bit.ly/3UP20M3

I have a script `main.js` which simply prints the current time on each page.

So i want the script to run on all the pages no matter what.

**Comment by arvgta** [comment]
Thanks.

I'll have a look at it tomorrow.

**Comment by khanakia** [comment]
I did make it work. Thanks :)
