### ISSUE TITLE
JS script executing 2 times

### ISSUE THREAD

**Issue by alexolliveira** [arvgta/ajaxify#233]
a - I have page X and page Y;
b - On page X , I have a javascript function;
(_So ​​far everything is ok... the javasript is fired only once)_
c- I leave page X and go to page Y,.
d - When I return to the page X, the js function is executing 2 times.

Any idea?

**Comment by arvgta** [comment]
Hi and thanks for bringing this up.

Which version of Ajaxify are you using?
Could you please check whether this is also the case with [older versions of Ajaxify](https://www.jsdelivr.com/package/gh/arvgta/ajaxify)?

Are you talking about an [inline script](https://4nf.org/inline-scripts/)?


Thanks!

**Comment by alexolliveira** [comment]
> Hi and thanks for bringing this up.
> 
> Which version of Ajaxify are you using? Could you please check whether this is also the case with [older versions of Ajaxify](https://www.jsdelivr.com/package/gh/arvgta/ajaxify)?
> 
> Are you talking about an [inline script](https://4nf.org/inline-scripts/)?
> 
> Thanks!

I'm using the version 8.2.6;
Yes... I'm have some scripts inside the tag <script>.

**Comment by alexolliveira** [comment]
I already solved. I put the script that was running twice - in a external js file. Anyway thank you! ;)

**Comment by arvgta** [comment]
While it is great that you got it going with that workaround, it would be useful to know, whether your error happens with previous Ajaxify versions as well.

Obviously, this would be a massive problem for many users, if it pertains to all inline scripts.
