### ISSUE TITLE
Consider also hosting releases on cdnjs.com

### ISSUE THREAD

**Issue by whispy** [arvgta/ajaxify#24]
I was running some network tests on my site, and I noticed that `ajaxify.min.js`, while one of the smallest files requested, took the longest to load. 

![2014-07-31_18-47-15](https://cloud.githubusercontent.com/assets/2874975/3772848/bd8c5332-1904-11e4-901b-a0297ff4505f.png)

I believe that it would be worth comparing [cdnjs'](www.cdnjs.com) speed to that of your server, @arvgta. It might give a noticeable boost.

**Comment by arvgta** [comment]
Hi Whispy!

Great idea!  I just tried briefly but could not find out how to submit a project:
When I press "Add Library" it takes me to the following URL:

https://github.com/cdnjs/cdnjs

There is also a note, that they're automating the submission of projects?

How does one submit a project there?

Thanks very much

**Comment by whispy** [comment]
Does this section help: https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library?

**Comment by arvgta** [comment]
Hi Whispy!

I've tried to open a corresponding pull-request: https://github.com/cdnjs/cdnjs/pull/3682

Please shout, if something's wrong with it - thanks!

**Comment by arvgta** [comment]
Not working :-( 

I goofed up by initially selecting the wrong folder:
- https://github.com/cdnjs/cdnjs/pull/3684

This didn't pass the Travis CI build process.
- I forgot the package.json

and didn't run
- npm test

I'll retry asap

Question:  How do you run

```
npm test
```

from the GitHub interface i.e. without the command line?

**Comment by whispy** [comment]
No idea, sorry! Hope you figure it out.

EDIT: Perhaps create an issue asking?

**Comment by arvgta** [comment]
Good idea:
- https://github.com/cdnjs/cdnjs/issues/3685

Thanks!

(Ajaxify is already hosted here but not kept up-to-date:

http://www.jsdelivr.com/#!jquery.ajaxify )

**Comment by arvgta** [comment]
Hey Whispy!

Would this do the job: 
- http://cdn.jsdelivr.net/jquery.ajaxify/4.4.2/ajaxify.min.js

if I find out how to keep it up-to-date?

For cdnjs, I'd have to setup Git und GitHub for Windows again, which I don't really want to do, because it is quite easy to corrupt the repositories that way.

So would jsdelivr.net do the job?

Thanks!

**Comment by arvgta** [comment]
Hi Whispy!

Please testdrive this: http://cdn.jsdelivr.net/jquery.ajaxify/4.7.4/ajaxify.min.js ...to see how the performance compares!

The update went well from their web-interface and by means of a bot.
I prefer that over the process at cdnjs.com.

I will update the documention at http://4nf.org/installation/ ...shortly

Thanks!

**Comment by whispy** [comment]
It seems to be loading around 2x more quickly! Nice!

**Comment by arvgta** [comment]
Hey Whispy,

that's great!  I've documented it on: 
- http://4nf.org/installation/

Any other ideas / issues?

**Comment by arvgta** [comment]
I can't find the landing page at its usual URL:
- http://www.jsdelivr.com/#!jquery.ajaxify

Any ideas why?

(this deeplink still works: 
- http://cdn.jsdelivr.net/jquery.ajaxify/4.7.4/ajaxify.min.js

)

**Comment by arvgta** [comment]
Both work now :-)

**Comment by arvgta** [comment]
PS:

Please use this one: 
- http://cdn.jsdelivr.net/jquery.ajaxify/4.7.5/ajaxify.min.js

Thanks!
