### ISSUE TITLE
Where is the source?

### ISSUE THREAD

**Issue by wolph** [arvgta/ajaxify#3]
It seems that there is only a minified version available here, where should I go to actually fork and modify the code?

**Comment by arvgta** [comment]
Thanks WoLpH!

http://forum.jquery.com/topic/new-plugin-history-api#14737000004733261

Could someone drop a post there, as this is a question that seems to pertain to lots of developers...

**Comment by arvgta** [comment]
Sorry, didn't mean to close this very valid issue!  Just re-opened it...

Otherwise, if you prefer to discuss it at a GitHub level, please proceed... :)

Love, Arvind.

**Comment by arvgta** [comment]
Source re-opened :)
