### ISSUE TITLE
form handling

### ISSUE THREAD

**Issue by wikiloops** [arvgta/ajaxify#32]
I have played around with the form-handling today - 
I am missing an option to disable individual forms from this, could you implement a listener that will prevent form handling of forms that carry the 'no-ajaxy' class, please?
I tried
`selector:"form:not(.no-ajaxy)"`,

but that didnt seem to work. Any ideas how to do that?

**Comment by arvgta** [comment]
Great idea!

Proposed solution:  I'll make

```
forms
```

accept a jQuery selection, instead of just true/false...

(I'm thinking of a jQuery selection as a _positive_ list)

Is that alright?

I would propose tackling this one first...

EDIT:  I've implemented it with a slight tweak only.  You now can pass a positive selection to forms.
Now, you could try:

```
forms: "form:not(.no-ajaxy)"
```

...again

Please use this [test file](http://4nf.org/ajaxify.js)

**Comment by wikiloops** [comment]
excellent, works right away :) Thank you!

**Comment by arvgta** [comment]
That's great!  Thank you, too!

I reckon I'll make the default:

```
forms: "form:not(.no-ajaxy)"
```

**Comment by wikiloops** [comment]
hmmm... form handling will break any paypal buttons one might have (those are forms for some reason) if not prevented by adding the no-ajaxy class. Maybe forms with cross domain targets should be turned off as a default?

**Comment by arvgta** [comment]
I agree - forgot to impose, that cross-domain targets are ignored.
Am taking a day off - will get to that tomorrow :)

**Comment by arvgta** [comment]
@wikiloops : fabulous ideas!  Keep on going, if you like.
Unfortunately, I'm a typical male, that can only do one thing after the other ;)

Let's check the `target` whether it's site internal and otherwise ignore it.
I would like to do that first (tomorrow).

Cheers!

**Comment by arvgta** [comment]
Fixed with the following code:

```
        function _internal(url) { 
            return url.substring(0,rootUrl.length) === rootUrl || !url.iO(':');
        }

        function _ajaxify_forms(mode) { 
            if (!forms) return false;

            var divs;
            divs = mode ? $gthis : $("body");
            divs.find(forms).filter(function() {
                return  _internal($(this).attr("action"));
            }).submit(...)
```

Where `rootUrl` is fetched as in Balupton's history.js with `getRootUrl()`...

@wikiloops: Please check against your PayPal buttons :)

Only file at the moment with the above functionality: http://4nf.org/ajaxify.js

**Comment by arvgta** [comment]
No news is good news, I suppose.  Please re-open if issue persists.
