### ISSUE TITLE
Input submit button

### ISSUE THREAD

**Issue by DaWe35** [arvgta/ajaxify#40]
Ajaxify not working when I click on this button:

<form action="save.php" id="asd" method="post">
<input type="submit" value="Save">
</form> 

What should I do?

**Comment by arvgta** [comment]
Hi,

could you please provide a link to your site?

**Comment by DaWe35** [comment]
I created an example page: http://ajaxify.coolhd.hu/

**Comment by arvgta** [comment]
As far as I can see, you're using Balupton's ajaxify-html5 and not the Ajaxify from 4nf.org??

Closing this issue...

**Comment by DaWe35** [comment]
Thanks! It's workink!
