### ISSUE TITLE
Preview feature

### ISSUE THREAD

**Issue by arvgta** [arvgta/ajaxify#5]
What do you think of an additional feature as a jQuery option "preview":
- Loads the divs to be swapped on hoverIntent, maybe in a layer on top of the page so that it goes away again, when the user navigates further?

A bit like the popular "image swap" (one of the first use-cases of JS), only with the content divs instead!

**Comment by arvgta** [comment]
Implemented and it works!

See it working on:  http://4nf.org/ and http://www.oeko-fakt.de/

It's a splendid effect :-)

**Comment by arvgta** [comment]
Any feedback, positive or negative?

**Comment by hisorange** [comment]
Aye, I just tested this like a hour ago, and I have to say the plugin is awesome "this is it!" :D
Preview is a really interesting idea and I actualy gona use at some page, but I am not sure it should be default set to true, except that its a really interesting development! ( when i hovered the sign out button got a bit surprised, ofc a no-ajax helps the problem )

**Comment by arvgta** [comment]
Hi there,

thanks very much for the great feedback!  Maybe I got too carried away in enthusiasm for the feature.  After all, I showed my folks, friends and other developers and they were very enthusiastic, mentioning that they've never seen anything similar before ;-)  (afaik this feature can easily be achieved using framesets, but not that easily without)

Sure, one of the main goals of Ajaxify is to require little customisation, taking a non-ajaxified site as "input".
Making Preview default sort of breaks that policy...

First thing I'll do is set default to "false" then.  There's room for overriding the default in future with any jQuery selection. (What do you think of that? - i.e: "false"==off (default), "true"==on and otherwise a selection of links as the "no-ajax" you're mentioning, not to preview)

It's worth mentioning, as you may have noticed, that the links of the content div(s) are not "previewified", by default anyway.

But you had an undesired effect with the sign-out button leading to a preview.  That could be worked-around by providing a jQuery selection not to preview, as the "no-ajax" override you suggested...

Yes, I agree, setting "Preview" to default is too aggressive and may irritate more users than the other way around.

I'll set it to "false" right now and maybe you could drop a note, what you think of the jQuery selection override for the future?

Cheers mate and many thanks once again!

**Comment by hisorange** [comment]
Since I just found this plugin, I can't give you a clear feedback about it, but I gona spend the night implement it to my current and old projects. 

For the preview question, I don't think its necessary to you to hardcode anything with this pretty nice selector feature the user can deicide which link are previewable and which not; Under this I mean there are many solution even on github which provide /ajaxification/ but while some trying to provide an "out of box" constrution where you only include the js file and rest are "done" (only if the site is pretty simple and follows their #content will be the only content container on the page structure and all link appers in the #nav only) or there are others where you actualy need to write more code to use than you write your own mechanism.

So I think this plugin has that great balance where you can handle the exceptions without hardcodeing.

``` js
$('#content').ajaxify({selector: '.upload-types a', preview:true});
$('#page').ajaxify({selector: '.mars a', preview:false});
```

I handled my exception with this simple code, so way to go!

**Comment by arvgta** [comment]
Thanks for your rapid reply!

That's incredible!  I never had the idea of "multi-plexing" the plugin...
However, I wouldn't advise anybody to do that, because the plugin has built-in "delta-loading" and the likes, which work in the header and across inline scripts and therefore expect the plugin to be called only once.

It's not really hard-coding, but rathermore a very generic option very much like the "selector" I would like to provide.
That really is my job!  (it's quite simple and I've provided something similar for "memoryoff", just as a list of links)

So before you charge ahead spending the whole night with the "double call" approach you're attempting, let me quickly see if I can implement a selector option cleanly.

(I quickly have to research the command for checking, whether a link is within a jQuery selection: 
https://forum.jquery.com/topic/how-to-check-whether-a-link-is-within-a-selection
)

Maybe analogue to memoryoff, I'll call it "previewoff" with default true, that accepts false or the selection.
Then in your use-case, you could call it like this:

$('#content, #page').ajaxify({selector: '.upload-types a', previewoff: '.mars a'});

**Comment by hisorange** [comment]
Sorry, I just trying to determine the best approach of ajax loading with my freshly writen php backend, and didn't do any test on the code above :D 

Out of the trail, I am not a great js coder, I can handle anything if really really necessary but I am rather a php coder, and wondering may you can help me with a simple theory.

Here you go the examples:

User clicks to login button in the navbar and the ajax will get a response like this 

``` html
<div id="content">login form</div>
```

This is the current workflow, but after the user executed a login not only the #content div will change but the navbar has too, right now every plugin handles this with a full page reload with ajax or without it. But what if i tell the js to expect different content changes too like:

``` js
$.ajaxifyTheory({ 
    selectors: ['#navbar .a', '#content .a'],
    expectedContents: ['#content', '#navbar', '#sidenav', '#otherChangeAbleContents'], // containers to be replaced if found.
    exceptSelector: '.not-ajax' // any link which contain this class will be skipped.
});});
```

Where the js checks which containers was responded and replace only/all of them. Ofc when the php sends back the response it gona look like this.

``` html
<div id="content">this is a user content or any page</div>
<div id="navbar"><a href="/me">Hello, Xyz</a></div>
```

Ofc this is a theorical thing but I wonder how could it happen. Sorry I gone really offtopic :D

EDIT: Nevermind just reading the documentation and seen its supported by the plugin :dancer:

**Comment by arvgta** [comment]
Thanks again for the very detailled reply!

Just a quick note, it's implemented as specified above - I've tested "previewoff" values: false / true and simple class.
It should now accept any jQuery selection as an override not to preview.

Need some sleep now, but very interesting - what are you thinking of? It sounds like you're aiming at abstracting the ajaxify process further.

Or are you aiming at updating even fewer parts of the page?  Or both?

Does what you described pertain only to the submission of button pressed items / forms / etc?

Am tired.  Talk to you soon - very interesting idea, but I must admit, I don't get whether you would like to generalise the approach further, or whether it's a specialisation.

My gut feeling says, as far as performance is concerned, the avoiding of a full-round trip is the biggest gain...

Is what you're describing above about enhancing the user experience or speed?

Cheers and good night :-)

**Comment by hisorange** [comment]
That was the best way to solve it ;)

I think gona answer your question later, when i fully understood the plugin capabilities, was just reading the interface page and found a missed line and realized with a little server side tweak I can optimize my backend to send the specific content only and nothing more.

Edit:

So, I was a bit surprised the script actually doing everything as I need, on php side I only sending out the changeing content and the plugin replaces only that so its smarter then me :+1:

**Comment by arvgta** [comment]
Hi Hisorange,

That's great, so I guess we'll carry on with issue #10 you kindly opened - thanks!

(the plugin replaces every div you specify in the master selector, but this will do nothing to the other container(s), that remain the same - transparently)

We'll leave this issue open though, alright, because your previous post was so interesting.  Maybe you can explain what your idea was at a later point...

**Comment by arvgta** [comment]
Evaluated as a useful feature, however turned to "false" by default.
