### ISSUE TITLE
No docs on the web

### ISSUE THREAD

**Issue by kapilgarg1996** [arvgta/ajaxify#57]
there are not any docs to get to know ajaxify. 4nf.org link is broken and swook.net link is not found. Please provide the documentation to learn and understand ajaxify.

**Comment by arvgta** [comment]
Hi, yes, http://4nf.org/ is experiencing a nasty downtime at the moment, due to the webhost.
That has been the case for several days now.
I have written the webhost - no reaction...

Sorry about that!

**Comment by kapilgarg1996** [comment]
Okay..Hope to get the docs soon. Why don't you write something in the wiki section. It would be easy to use this amazing plugin with proper instructions.

**Comment by arvgta** [comment]
I hope, that it is rather unusual in the long run for a renowned webhost like the one I'm using to default.  A good idea to use the GitHub Wiki, thanks! It's just that it would be a bit redundant and require extra maintenance.

(It's the first such severe downtime of the webhost I've noticed since at least 2005 - to be fair)

**Comment by kapilgarg1996** [comment]
Okay..Then lets wait for the host to be resolved the issues.

**Comment by arvgta** [comment]
(What I could definitely do is embed the documentation of the most important piece - the interface - in the source code)

**Comment by kapilgarg1996** [comment]
Yeah that would be awesome..The configurable options

**Comment by arvgta** [comment]
Alright - thanks!  I now have that up on top of my todo-list :)

**Comment by arvgta** [comment]
Please see #58

**Comment by kapilgarg1996** [comment]
@arvgta perfect :+1: Thanks a lot.
Now going to close the issue. :sweat_smile:
