### ISSUE TITLE
Bootstrap 3 not properly reponse to viewport after animation

### ISSUE THREAD

**Issue by ceresyuyi** [arvgta/ajaxify#94]
Description:
- After aniTime and aniParams had been set 
  ( example: aniTime: 200 , aniParams : {opacity:0, width:"100%", height:"100%"} ), bootstrap will
  create large space when adapt to mobile view.

Any solution to work around this?

**Comment by oliverff** [comment]
Vielen Dank für Ihre Anfrage!

Wir melden uns umgehend.

kreakurs.de

**Comment by MysticFalls** [comment]
Vielen Dank für Ihre Anfrage!

Wir melden uns umgehend.

kreakurs.de

**Comment by david-bowie** [comment]
Vielen Dank für Ihre Anfrage!

Wir melden uns umgehend.

kreakurs.de

**Comment by arvgta** [comment]
[Please have a look at this first](https://github.com/arvgta/ajaxify/issues/22)...  Thanks!

> edit:
> including bootstrap.js AFTER ajaxify.js is the solution to a problem

If the problem persists, please make sure you're using the [latest version of Ajaxify](https://cdn.jsdelivr.net/jquery.ajaxify/6.2.0/ajaxify.min.js)

**Comment by arvgta** [comment]
Please re-open, if you have new findings...
