### ISSUE TITLE
No js file on npm

### ISSUE THREAD

**Issue by kennynaoh** [arvgta/ajaxify#95]
Hello @arvgta ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
I install the ajaxify package on [npm](https://www.npmjs.com/package/ajaxify).
But there are only `package.js` and `README.md` file.
Maybe you could publish the `ajaxify.js` and `ajaxify.min.js` on npm.
Thanks very much!

https://github.com/cdnjs/cdnjs/issues/7941

**Comment by arvgta** [comment]
Hi Kennynaoh,

thanks a bunch for considering to host Ajaxify on cdnjs!

I thought that I had followed [these instructions](http://blog.npmjs.org/post/111475741445/publishing-your-jquery-plugin-to-npm-the-quick) correctly?
What has to be done, to publish the two source files as well?
(Just drop them in the same folder as the other two files before running `npm publish`
I suppose?)

**Comment by kennynaoh** [comment]
You should publish files which you want to host.
Thanks!

**Comment by arvgta** [comment]
Thanks!  It might take a few days, because I'm in the middle of nowhere right now...

**Comment by kennynaoh** [comment]
Could you remind me if it is done?
Thanks!

**Comment by arvgta** [comment]
Yes, of course.
Thanks!

**Comment by arvgta** [comment]
@kennynaoh [Any better](https://www.npmjs.com/package/ajaxify)?
Please let me know, if it's still unsatisfactory...  Thanks!

**Comment by kennynaoh** [comment]
Looks great, thanks

**Comment by arvgta** [comment]
I'm the one to say thanks!
Great stuff!
